export enum ProductCategory {
    ELETRONICOS = "ELETRONICOS",
    ACESSORIOS = "ACESSORIOS",
    PERIFERICOS = "PERIFERICOS",
    MOVEIS = "MOVEIS",
    AUDIO = "AUDIO",
    UNCATEGORIZED = "UNCATEGORIZED"
}